version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    ports:
      - 5959:5432
    volumes:
      - pg-data:/docker/

volumes:
  pg-data:
